let data = [
    {
        name: "Collection 1",
        content: [
            {
                type: "link",
                href: "https://web.whatsapp.com/",
                title: "WhatsApp",
                cover: "https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami",
                title: "mienaiyami (Sukoon) · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/collections-chrome-extension",
                title: "GitHub - mienaiyami/collections-chrome-extension: chromium extension to make collection of links",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/",
                title: "GitHub: Where the world builds software · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/react-todo-app",
                title: "GitHub - mienaiyami/react-todo-app",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://wizardly-shockley-99ad62.netlify.app/",
                title: "TODO App",
                cover: "https://wizardly-shockley-99ad62.netlify.app/favicon.ico",
            },
            {
                type: "link",
                href: "https://web.whatsapp.com/",
                title: "WhatsApp",
                cover: "https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami",
                title: "mienaiyami (Sukoon) · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/collections-chrome-extension",
                title: "GitHub - mienaiyami/collections-chrome-extension: chromium extension to make collection of links",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
        ],
    },
    {
        name: "Collection",
        cover: "",
        content: [
            {
                type: "link",
                title: "dddd",
                cover: "",
                href: "https://github.com/",
            },
        ],
    },
    {
        name: "Collection 2",
        cover: "",
        content: [],
    },
    {
        name: "Collection 3",
        content: [
            {
                type: "link",
                href: "https://web.whatsapp.com/",
                title: "WhatsApp",
                cover: "https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami",
                title: "mienaiyami (Sukoon) · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/collections-chrome-extension",
                title: "GitHub - mienaiyami/collections-chrome-extension: chromium extension to make collection of links",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/",
                title: "GitHub: Where the world builds software · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/react-todo-app",
                title: "GitHub - mienaiyami/react-todo-app",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://wizardly-shockley-99ad62.netlify.app/",
                title: "TODO App",
                cover: "https://wizardly-shockley-99ad62.netlify.app/favicon.ico",
            },
            {
                type: "link",
                href: "https://web.whatsapp.com/",
                title: "WhatsApp",
                cover: "https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami",
                title: "mienaiyami (Sukoon) · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/collections-chrome-extension",
                title: "GitHub - mienaiyami/collections-chrome-extension: chromium extension to make collection of links",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
        ],
    },
    {
        name: "Collection 3",
        content: [
            {
                type: "link",
                href: "https://web.whatsapp.com/",
                title: "WhatsApp",
                cover: "https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami",
                title: "mienaiyami (Sukoon) · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/collections-chrome-extension",
                title: "GitHub - mienaiyami/collections-chrome-extension: chromium extension to make collection of links",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/",
                title: "GitHub: Where the world builds software · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/react-todo-app",
                title: "GitHub - mienaiyami/react-todo-app",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://wizardly-shockley-99ad62.netlify.app/",
                title: "TODO App",
                cover: "https://wizardly-shockley-99ad62.netlify.app/favicon.ico",
            },
            {
                type: "link",
                href: "https://web.whatsapp.com/",
                title: "WhatsApp",
                cover: "https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami",
                title: "mienaiyami (Sukoon) · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/collections-chrome-extension",
                title: "GitHub - mienaiyami/collections-chrome-extension: chromium extension to make collection of links",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
        ],
    },
    {
        name: "Collection 3",
        content: [
            {
                type: "link",
                href: "https://web.whatsapp.com/",
                title: "WhatsApp",
                cover: "https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami",
                title: "mienaiyami (Sukoon) · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/collections-chrome-extension",
                title: "GitHub - mienaiyami/collections-chrome-extension: chromium extension to make collection of links",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/",
                title: "GitHub: Where the world builds software · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/react-todo-app",
                title: "GitHub - mienaiyami/react-todo-app",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://wizardly-shockley-99ad62.netlify.app/",
                title: "TODO App",
                cover: "https://wizardly-shockley-99ad62.netlify.app/favicon.ico",
            },
            {
                type: "link",
                href: "https://web.whatsapp.com/",
                title: "WhatsApp",
                cover: "https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami",
                title: "mienaiyami (Sukoon) · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/collections-chrome-extension",
                title: "GitHub - mienaiyami/collections-chrome-extension: chromium extension to make collection of links",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
        ],
    },
    {
        name: "Collection 3",
        content: [
            {
                type: "link",
                href: "https://web.whatsapp.com/",
                title: "WhatsApp",
                cover: "https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami",
                title: "mienaiyami (Sukoon) · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/collections-chrome-extension",
                title: "GitHub - mienaiyami/collections-chrome-extension: chromium extension to make collection of links",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/",
                title: "GitHub: Where the world builds software · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/react-todo-app",
                title: "GitHub - mienaiyami/react-todo-app",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://wizardly-shockley-99ad62.netlify.app/",
                title: "TODO App",
                cover: "https://wizardly-shockley-99ad62.netlify.app/favicon.ico",
            },
            {
                type: "link",
                href: "https://web.whatsapp.com/",
                title: "WhatsApp",
                cover: "https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami",
                title: "mienaiyami (Sukoon) · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/collections-chrome-extension",
                title: "GitHub - mienaiyami/collections-chrome-extension: chromium extension to make collection of links",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
        ],
    },
    {
        name: "Collection 3",
        content: [
            {
                type: "link",
                href: "https://web.whatsapp.com/",
                title: "WhatsApp",
                cover: "https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami",
                title: "mienaiyami (Sukoon) · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/collections-chrome-extension",
                title: "GitHub - mienaiyami/collections-chrome-extension: chromium extension to make collection of links",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/",
                title: "GitHub: Where the world builds software · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/react-todo-app",
                title: "GitHub - mienaiyami/react-todo-app",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://wizardly-shockley-99ad62.netlify.app/",
                title: "TODO App",
                cover: "https://wizardly-shockley-99ad62.netlify.app/favicon.ico",
            },
            {
                type: "link",
                href: "https://web.whatsapp.com/",
                title: "WhatsApp",
                cover: "https://web.whatsapp.com/img/favicon_c5088e888c97ad440a61d247596f88e5.png",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami",
                title: "mienaiyami (Sukoon) · GitHub",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
            {
                type: "link",
                href: "https://github.com/mienaiyami/collections-chrome-extension",
                title: "GitHub - mienaiyami/collections-chrome-extension: chromium extension to make collection of links",
                cover: "https://github.githubassets.com/favicons/favicon-dark.svg",
            },
        ],
    },
];
export default data;
